robots:
  left_hand_robot:
    robot_connected: false
    communication_method: 'UART'
    communication_channel_identifier: 'COM7'
    hand_type: 'left'
    start_robot: false
    reset_on_start: 0
    streaming_frequency: 20  # data/seconds
    calibrate: false


  right_hand_robot:
    robot_connected: true
    communication_method: 'UART'
    communication_channel_identifier: 'COM7'
    hand_type: 'right'
    start_robot: false
    reset_on_start: 0
    streaming_frequency: 20  # data/seconds
    calibrate: false